export const ARTICLE_LIST_FETCH_REQUEST = "ARTICLE_LIST_FETCH_REQUEST";
export const ARTICLE_LIST_FETCH_SUCCESS = "ARTICLE_LIST_FETCH_SUCCESS";
export const ARTICLE_LIST_FETCH_FAILURE = "ARTICLE_LIST_FETCH_FAILURE";
